name: Lint (Yarn + Nix)

on:
  pull_request:
    branches: [main]

jobs:
  alejandra:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nix Cache
        uses: actions/cache@v4
        with:
          path: /nix
          key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: alejandra check
        run: nix develop -c alejandra --check .

  eslint:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nix Cache
        uses: actions/cache@v4
        with:
          path: /nix
          key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Yarn Cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: yarn install
        run: nix develop -c yarn install --frozen-lockfile

      - name: Run lint
        run: nix develop -c yarn lint
