services:
  db:
    image: postgres:16
    container_name: __APP_NAME__-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - __APP_NAME___pgdata:/var/lib/postgresql/data

volumes:
  __APP_NAME___pgdata:
